---
include:
  - metrics/compose.yaml
services:
  stella:
    build: ghcr.io/CelestialCrafter/stella:master
    hostname: stella
    ports:
      - 8000:80
    environment:
      PYROSCOPE_ADDRESS: http://pyroscope:4040
    volumes:
      - ./.env:/app/.env
      - ./stella.db:/app/stella.db
    networks:
      - metrics
      - stella
networks:
  stella:
